#delete all vlans
- name: Delete attributes VLANs
  hosts: switches 
  connection: network_cli
  gather_facts: false

  vars:
    ansible_command_timeout: 60
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: cisco123 
  tasks: 
    - name: Delete VLANs
      cisco.ios.ios_vlans:
        #line to delete certain vlans
        config:
          - vlan_id: 10
          - vlan_id: 20
        state: deleted
