---
- name: Merge provided configuration with device configuration
  hosts: switches 
  connection: network_cli
  gather_facts: false

  vars:
    ansible_command_timeout: 60
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: cisco123
  tasks:
    - name: configure VLANs 
      cisco.ios.ios_vlans:
        config:
          - name: Vlan_10
            vlan_id: 10
            state: active
            shutdown: disabled
            remote_span: true
          - name: Vlan_20
            vlan_id: 20
            mtu: 610
            state: active
            shutdown: enabled
          - name: Vlan_30
            vlan_id: 30
            state: suspend
            shutdown: enabled
      state: merged