---
- name: Merge provided configuration with device configuration
  hosts: switches 
  connection: network_cli
  gather_facts: false

  vars:
    ansible_command_timeout: 60
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: cisco123
  tasks:
    - name: Merge provided configuration with device configuration
      cisco.ios.ios_vlans:
        config:
          - name: "Vlan_{{ item }}"
            vlan_id: "{{ item }}"
            state: active
            shutdown: disabled
        state: merged
      loop: "{{ range(10, 40, 10) | list }}"